### ISSUE TITLE
Supporting  MID 15KTL3-X 

### ISSUE THREAD

**Issue by mikaabra** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#4]
Hi,

I have a Growatt MID 15KTL3-X. It seems to not currently be supported by this project (when trying to add it, it says "device didn't respond"). I've found the modbus registers for it and have it working by using the following config in HA:

```
modbus:
  - name: "growatt-tcp"
    type: tcp
    host: 192.168.200.230
    port: 502
    sensors:
      - name: "growatt-tcp power"
        unit_of_measurement: W
        device_class: power
        slave: 1
        address: 1
        input_type: input
        scan_interval: 15
        data_type: int32
        count: 2
        scale: 0.1

```

This maps to the modbus input registers as found in the PDF at [https://www.photovoltaicsolar.in/Growatt_Manual/MAX%20Series%20Modbus%20RTU%20Protocol.pdf](url)

```
First group
--
0. | Inverter Status | Inverter run state | 0:waiting, 1:normal, 3:fault
1. | Ppv H | Input power (high) | 0.1W
2. | Ppv L | Input power (low) | 0.1W

```

This is similar but not the same to the ones already in this project, which seems to be float instead of int32.

```
    GrowattDeviceRegisters(
        name=ATTR_INPUT_POWER, register=1, value_type=float, length=2
    ),
```

When I use a modbus client directly to the device I get the following information which matches above pdf:

```
$ docker run --rm oitc/modbus-client:latest -s 192.168.200.230 -p 502 -t 4 -r 0 -l 4 -i 1
           HEX16  UINT16  INT16               BIT       HEX32  \
register                                                        
30000     0x0001       1      1  0000000000000001  0x00010000   
30001     0x0002       2      2  0000000000000010  0x00020001   
30002     0x5502   21762  21762  0101010100000010  0x55020002   
30003     0x18D0    6352   6352  0001100011010000  0x18D05502   

```

Now, I can go through and manually adding all of these registers in my HA configuration.yaml and solve my own problem, but I'd rather solve it for everybody by contributing to this project.

Do you believe my inverter uses a different protocol version other than the 1.20 and 3.15 already supported so my inverter would need to add a new protocol version? So it'd basically need a new file to inverter_120.py and inverter_315.py?

If it's needed, I'd like to do the work to add inverter.py file for my inverter but I would need help getting started. I can run this modbus-client (or anything else) to help identifying the device to help start the work.
